# Database settings
db_settings:
  user: 'cn_changes_monitor'
  password: 'cn_changes_monitor_pw'
  host: 'localhost'
  database: 'centralnotice_changes_monitor'

# CentralNotice infrastructure wiki, to be called via Web API
# Leave this whole section commented to default to WMF Meta wiki.
wiki:
  host: 'localhost:8080'
  scriptpath: '/w'

# Changes to emit alerts on
alert_patterns:
  - name: 'Added or removed links'
    added: 'http(s)://'
    removed: 'http(s)://'
